Plug 'easymotion/vim-easymotion'
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-surround'
Plug 'terryma/vim-multiple-cursors'
Plug 'dominikduda/vim_current_word'
Plug 'scrooloose/nerdcommenter'
Plug 'ervandew/supertab'