" MMP 'iliubang/yadracula'
" MMP 'liuchengxu/eleline.vim'
MMP 'vim-airline/vim-airline'
" MMP 'mgee/lightline-bufferline'
" MMP 'itchyny/lightline.vim'
MMP 'mhinz/vim-startify'
MMP 'morhetz/gruvbox'
MMP 'sheerun/vim-polyglot'
